/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * recibo.java
 *
 * Created on 10-sep-2014, 0:59:48
 */
package smapasab;

/**
 *
 * @author Eduardo
 */
public class recibo extends javax.swing.JInternalFrame {

    /** Creates new form recibo */
    public recibo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtpmap = new javax.swing.JTextField();
        txtvence = new javax.swing.JTextField();
        txtlectAnt = new javax.swing.JTextField();
        txtlectAct = new javax.swing.JTextField();
        txtconsumo = new javax.swing.JTextField();
        textfemi = new javax.swing.JTextField();
        txtrezap = new javax.swing.JTextField();
        txtrecap = new javax.swing.JTextField();
        txtrezalc = new javax.swing.JTextField();
        txtrecalc = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        txtpmalc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcuenta = new javax.swing.JTextField();
        txtflimite = new javax.swing.JTextField();
        txtconsumido = new javax.swing.JTextField();
        txtcuen = new javax.swing.JTextField();
        txtreza = new javax.swing.JTextField();
        txtreca = new javax.swing.JTextField();
        txtpma = new javax.swing.JTextField();
        txtrezl = new javax.swing.JTextField();
        txtrecl = new javax.swing.JTextField();
        txtpml = new javax.swing.JTextField();
        txttot = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtpmap1 = new javax.swing.JTextField();
        txtvence1 = new javax.swing.JTextField();
        txtlectAnt1 = new javax.swing.JTextField();
        txtlectAct1 = new javax.swing.JTextField();
        txtconsumo1 = new javax.swing.JTextField();
        textfemi1 = new javax.swing.JTextField();
        txtrezap1 = new javax.swing.JTextField();
        txtrecap1 = new javax.swing.JTextField();
        txtrezalc1 = new javax.swing.JTextField();
        txtrecalc1 = new javax.swing.JTextField();
        txttotal1 = new javax.swing.JTextField();
        txtpmalc1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcuenta1 = new javax.swing.JTextField();
        txtflimite1 = new javax.swing.JTextField();
        txtconsumido1 = new javax.swing.JTextField();
        txtcuen1 = new javax.swing.JTextField();
        txtreza1 = new javax.swing.JTextField();
        txtreca1 = new javax.swing.JTextField();
        txtpma1 = new javax.swing.JTextField();
        txtrezl1 = new javax.swing.JTextField();
        txtrecl1 = new javax.swing.JTextField();
        txtpml1 = new javax.swing.JTextField();
        txttot1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtpmap2 = new javax.swing.JTextField();
        txtvence2 = new javax.swing.JTextField();
        txtlectAnt2 = new javax.swing.JTextField();
        txtlectAct2 = new javax.swing.JTextField();
        txtconsumo2 = new javax.swing.JTextField();
        textfemi2 = new javax.swing.JTextField();
        txtrezap2 = new javax.swing.JTextField();
        txtrecap2 = new javax.swing.JTextField();
        txtrezalc2 = new javax.swing.JTextField();
        txtrecalc2 = new javax.swing.JTextField();
        txttotal2 = new javax.swing.JTextField();
        txtpmalc2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcuenta2 = new javax.swing.JTextField();
        txtflimite2 = new javax.swing.JTextField();
        txtconsumido2 = new javax.swing.JTextField();
        txtcuen2 = new javax.swing.JTextField();
        txtreza2 = new javax.swing.JTextField();
        txtreca2 = new javax.swing.JTextField();
        txtpma2 = new javax.swing.JTextField();
        txtrezl2 = new javax.swing.JTextField();
        txtrecl2 = new javax.swing.JTextField();
        txtpml2 = new javax.swing.JTextField();
        txttot2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        pnlboton = new javax.swing.JPanel();

        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setText("SISTEMA MUNICIPAL DE AGUA POTABLE Y ALCANTARIRALLADOS, EL SABINO,GTO.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 0, 404, 14);

        txtpmap.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel2.add(txtpmap);
        txtpmap.setBounds(450, 70, 94, 40);

        txtvence.setText("hola");
        txtvence.setBorder(javax.swing.BorderFactory.createTitledBorder("Vence"));
        jPanel2.add(txtvence);
        txtvence.setBounds(90, 20, 94, 39);

        txtlectAnt.setBorder(javax.swing.BorderFactory.createTitledBorder("Lect. Anterior"));
        jPanel2.add(txtlectAnt);
        txtlectAnt.setBounds(180, 20, 94, 39);

        txtlectAct.setBorder(javax.swing.BorderFactory.createTitledBorder("Lect. Actual"));
        jPanel2.add(txtlectAct);
        txtlectAct.setBounds(270, 20, 94, 39);

        txtconsumo.setBorder(javax.swing.BorderFactory.createTitledBorder("Consumo"));
        jPanel2.add(txtconsumo);
        txtconsumo.setBounds(360, 20, 94, 39);

        textfemi.setText("hola");
        textfemi.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha emisión"));
        jPanel2.add(textfemi);
        textfemi.setBounds(0, 20, 94, 40);

        txtrezap.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos AP"));
        jPanel2.add(txtrezap);
        txtrezap.setBounds(270, 70, 94, 40);

        txtrecap.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos AP"));
        txtrecap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecapActionPerformed(evt);
            }
        });
        jPanel2.add(txtrecap);
        txtrecap.setBounds(360, 70, 94, 40);

        txtrezalc.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos ALC"));
        txtrezalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrezalcActionPerformed(evt);
            }
        });
        jPanel2.add(txtrezalc);
        txtrezalc.setBounds(270, 110, 94, 40);

        txtrecalc.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos ALC"));
        jPanel2.add(txtrecalc);
        txtrecalc.setBounds(360, 110, 94, 40);

        txttotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        jPanel2.add(txttotal);
        txttotal.setBounds(450, 160, 94, 40);

        txtpmalc.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel2.add(txtpmalc);
        txtpmalc.setBounds(450, 110, 94, 40);

        jLabel2.setText("S.M.A.P.A.");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(560, 0, 90, 14);

        txtcuenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));
        jPanel2.add(txtcuenta);
        txtcuenta.setBounds(450, 20, 94, 39);

        txtflimite.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Limite"));
        jPanel2.add(txtflimite);
        txtflimite.setBounds(560, 20, 94, 39);

        txtconsumido.setBorder(javax.swing.BorderFactory.createTitledBorder("Consumo"));
        jPanel2.add(txtconsumido);
        txtconsumido.setBounds(650, 20, 94, 39);

        txtcuen.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));
        jPanel2.add(txtcuen);
        txtcuen.setBounds(740, 20, 94, 39);

        txtreza.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos AP"));
        jPanel2.add(txtreza);
        txtreza.setBounds(560, 70, 94, 40);

        txtreca.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos AP"));
        txtreca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecaActionPerformed(evt);
            }
        });
        jPanel2.add(txtreca);
        txtreca.setBounds(650, 70, 94, 40);

        txtpma.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel2.add(txtpma);
        txtpma.setBounds(740, 70, 94, 40);

        txtrezl.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos ALC"));
        txtrezl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrezlActionPerformed(evt);
            }
        });
        jPanel2.add(txtrezl);
        txtrezl.setBounds(560, 110, 94, 40);

        txtrecl.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos ALC"));
        jPanel2.add(txtrecl);
        txtrecl.setBounds(650, 110, 94, 40);

        txtpml.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel2.add(txtpml);
        txtpml.setBounds(740, 110, 94, 40);

        txttot.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        jPanel2.add(txttot);
        txttot.setBounds(740, 160, 94, 40);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(20, 160, 180, 10);

        jLabel7.setText("SELLO Y FIRMA DEL CAJERO");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 170, 230, 14);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 850, 210);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel3.setText("SISTEMA MUNICIPAL DE AGUA POTABLE Y ALCANTARIRALLADOS, EL SABINO,GTO.");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 0, 404, 14);

        txtpmap1.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel3.add(txtpmap1);
        txtpmap1.setBounds(450, 70, 94, 40);

        txtvence1.setBorder(javax.swing.BorderFactory.createTitledBorder("Vence"));
        jPanel3.add(txtvence1);
        txtvence1.setBounds(90, 20, 94, 39);

        txtlectAnt1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lect. Anterior"));
        jPanel3.add(txtlectAnt1);
        txtlectAnt1.setBounds(180, 20, 94, 39);

        txtlectAct1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lect. Actual"));
        jPanel3.add(txtlectAct1);
        txtlectAct1.setBounds(270, 20, 94, 39);

        txtconsumo1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consumo"));
        jPanel3.add(txtconsumo1);
        txtconsumo1.setBounds(360, 20, 94, 39);

        textfemi1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha emisión"));
        jPanel3.add(textfemi1);
        textfemi1.setBounds(0, 20, 94, 40);

        txtrezap1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos AP"));
        jPanel3.add(txtrezap1);
        txtrezap1.setBounds(270, 70, 94, 40);

        txtrecap1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos AP"));
        txtrecap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecap1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtrecap1);
        txtrecap1.setBounds(360, 70, 94, 40);

        txtrezalc1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos ALC"));
        txtrezalc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrezalc1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtrezalc1);
        txtrezalc1.setBounds(270, 110, 94, 40);

        txtrecalc1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos ALC"));
        jPanel3.add(txtrecalc1);
        txtrecalc1.setBounds(360, 110, 94, 40);

        txttotal1.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        jPanel3.add(txttotal1);
        txttotal1.setBounds(450, 160, 94, 40);

        txtpmalc1.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel3.add(txtpmalc1);
        txtpmalc1.setBounds(450, 110, 94, 40);

        jLabel4.setText("S.M.A.P.A.");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(560, 0, 90, 14);

        txtcuenta1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));
        jPanel3.add(txtcuenta1);
        txtcuenta1.setBounds(450, 20, 94, 39);

        txtflimite1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Limite"));
        jPanel3.add(txtflimite1);
        txtflimite1.setBounds(560, 20, 94, 39);

        txtconsumido1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consumo"));
        jPanel3.add(txtconsumido1);
        txtconsumido1.setBounds(650, 20, 94, 39);

        txtcuen1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));
        jPanel3.add(txtcuen1);
        txtcuen1.setBounds(740, 20, 94, 39);

        txtreza1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos AP"));
        jPanel3.add(txtreza1);
        txtreza1.setBounds(560, 70, 94, 40);

        txtreca1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos AP"));
        txtreca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreca1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtreca1);
        txtreca1.setBounds(650, 70, 94, 40);

        txtpma1.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel3.add(txtpma1);
        txtpma1.setBounds(740, 70, 94, 40);

        txtrezl1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos ALC"));
        txtrezl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrezl1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtrezl1);
        txtrezl1.setBounds(560, 110, 94, 40);

        txtrecl1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos ALC"));
        jPanel3.add(txtrecl1);
        txtrecl1.setBounds(650, 110, 94, 40);

        txtpml1.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel3.add(txtpml1);
        txtpml1.setBounds(740, 110, 94, 40);

        txttot1.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        jPanel3.add(txttot1);
        txttot1.setBounds(740, 160, 94, 40);

        jLabel8.setText("SELLO Y FIRMA DEL CAJERO");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 170, 270, 14);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(30, 160, 180, 10);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 210, 850, 210);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel5.setText("SISTEMA MUNICIPAL DE AGUA POTABLE Y ALCANTARIRALLADOS, EL SABINO,GTO.");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 0, 404, 14);

        txtpmap2.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel4.add(txtpmap2);
        txtpmap2.setBounds(450, 70, 94, 40);

        txtvence2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vence"));
        jPanel4.add(txtvence2);
        txtvence2.setBounds(90, 20, 94, 39);

        txtlectAnt2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lect. Anterior"));
        jPanel4.add(txtlectAnt2);
        txtlectAnt2.setBounds(180, 20, 94, 39);

        txtlectAct2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lect. Actual"));
        jPanel4.add(txtlectAct2);
        txtlectAct2.setBounds(270, 20, 94, 39);

        txtconsumo2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consumo"));
        jPanel4.add(txtconsumo2);
        txtconsumo2.setBounds(360, 20, 94, 39);

        textfemi2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha emisión"));
        jPanel4.add(textfemi2);
        textfemi2.setBounds(0, 20, 94, 40);

        txtrezap2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos AP"));
        jPanel4.add(txtrezap2);
        txtrezap2.setBounds(270, 70, 94, 40);

        txtrecap2.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos AP"));
        txtrecap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecap2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtrecap2);
        txtrecap2.setBounds(360, 70, 94, 40);

        txtrezalc2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos ALC"));
        txtrezalc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrezalc2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtrezalc2);
        txtrezalc2.setBounds(270, 110, 94, 40);

        txtrecalc2.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos ALC"));
        jPanel4.add(txtrecalc2);
        txtrecalc2.setBounds(360, 110, 94, 40);

        txttotal2.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        jPanel4.add(txttotal2);
        txttotal2.setBounds(450, 160, 94, 40);

        txtpmalc2.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel4.add(txtpmalc2);
        txtpmalc2.setBounds(450, 110, 94, 40);

        jLabel6.setText("S.M.A.P.A.");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(560, 0, 90, 14);

        txtcuenta2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));
        jPanel4.add(txtcuenta2);
        txtcuenta2.setBounds(450, 20, 94, 39);

        txtflimite2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Limite"));
        jPanel4.add(txtflimite2);
        txtflimite2.setBounds(560, 20, 94, 39);

        txtconsumido2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consumo"));
        jPanel4.add(txtconsumido2);
        txtconsumido2.setBounds(650, 20, 94, 39);

        txtcuen2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));
        jPanel4.add(txtcuen2);
        txtcuen2.setBounds(740, 20, 94, 39);

        txtreza2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos AP"));
        jPanel4.add(txtreza2);
        txtreza2.setBounds(560, 70, 94, 40);

        txtreca2.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos AP"));
        txtreca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreca2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtreca2);
        txtreca2.setBounds(650, 70, 94, 40);

        txtpma2.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel4.add(txtpma2);
        txtpma2.setBounds(740, 70, 94, 40);

        txtrezl2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezagos ALC"));
        txtrezl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrezl2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtrezl2);
        txtrezl2.setBounds(560, 110, 94, 40);

        txtrecl2.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos ALC"));
        jPanel4.add(txtrecl2);
        txtrecl2.setBounds(650, 110, 94, 40);

        txtpml2.setBorder(javax.swing.BorderFactory.createTitledBorder("Presente mes"));
        jPanel4.add(txtpml2);
        txtpml2.setBounds(740, 110, 94, 40);

        txttot2.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        jPanel4.add(txttot2);
        txttot2.setBounds(740, 160, 94, 40);
        jPanel4.add(jSeparator3);
        jSeparator3.setBounds(20, 160, 180, 10);

        jLabel9.setText("SELLO Y FIRMA DEL CAJERO");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(30, 170, 260, 14);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 420, 850, 220);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 116, 845, 653);

        javax.swing.GroupLayout pnlbotonLayout = new javax.swing.GroupLayout(pnlboton);
        pnlboton.setLayout(pnlbotonLayout);
        pnlbotonLayout.setHorizontalGroup(
            pnlbotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        pnlbotonLayout.setVerticalGroup(
            pnlbotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pnlboton);
        pnlboton.setBounds(20, 10, 110, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrecapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrecapActionPerformed

    private void txtrezalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrezalcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrezalcActionPerformed

    private void txtrecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrecaActionPerformed

    private void txtrezlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrezlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrezlActionPerformed

    private void txtrecap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrecap1ActionPerformed

    private void txtrezalc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrezalc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrezalc1ActionPerformed

    private void txtreca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreca1ActionPerformed

    private void txtrezl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrezl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrezl1ActionPerformed

    private void txtrecap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecap2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrecap2ActionPerformed

    private void txtrezalc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrezalc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrezalc2ActionPerformed

    private void txtreca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreca2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreca2ActionPerformed

    private void txtrezl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrezl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrezl2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnlboton;
    private javax.swing.JTextField textfemi;
    private javax.swing.JTextField textfemi1;
    private javax.swing.JTextField textfemi2;
    private javax.swing.JTextField txtconsumido;
    private javax.swing.JTextField txtconsumido1;
    private javax.swing.JTextField txtconsumido2;
    private javax.swing.JTextField txtconsumo;
    private javax.swing.JTextField txtconsumo1;
    private javax.swing.JTextField txtconsumo2;
    private javax.swing.JTextField txtcuen;
    private javax.swing.JTextField txtcuen1;
    private javax.swing.JTextField txtcuen2;
    private javax.swing.JTextField txtcuenta;
    private javax.swing.JTextField txtcuenta1;
    private javax.swing.JTextField txtcuenta2;
    private javax.swing.JTextField txtflimite;
    private javax.swing.JTextField txtflimite1;
    private javax.swing.JTextField txtflimite2;
    private javax.swing.JTextField txtlectAct;
    private javax.swing.JTextField txtlectAct1;
    private javax.swing.JTextField txtlectAct2;
    private javax.swing.JTextField txtlectAnt;
    private javax.swing.JTextField txtlectAnt1;
    private javax.swing.JTextField txtlectAnt2;
    private javax.swing.JTextField txtpma;
    private javax.swing.JTextField txtpma1;
    private javax.swing.JTextField txtpma2;
    private javax.swing.JTextField txtpmalc;
    private javax.swing.JTextField txtpmalc1;
    private javax.swing.JTextField txtpmalc2;
    private javax.swing.JTextField txtpmap;
    private javax.swing.JTextField txtpmap1;
    private javax.swing.JTextField txtpmap2;
    private javax.swing.JTextField txtpml;
    private javax.swing.JTextField txtpml1;
    private javax.swing.JTextField txtpml2;
    private javax.swing.JTextField txtreca;
    private javax.swing.JTextField txtreca1;
    private javax.swing.JTextField txtreca2;
    private javax.swing.JTextField txtrecalc;
    private javax.swing.JTextField txtrecalc1;
    private javax.swing.JTextField txtrecalc2;
    private javax.swing.JTextField txtrecap;
    private javax.swing.JTextField txtrecap1;
    private javax.swing.JTextField txtrecap2;
    private javax.swing.JTextField txtrecl;
    private javax.swing.JTextField txtrecl1;
    private javax.swing.JTextField txtrecl2;
    private javax.swing.JTextField txtreza;
    private javax.swing.JTextField txtreza1;
    private javax.swing.JTextField txtreza2;
    private javax.swing.JTextField txtrezalc;
    private javax.swing.JTextField txtrezalc1;
    private javax.swing.JTextField txtrezalc2;
    private javax.swing.JTextField txtrezap;
    private javax.swing.JTextField txtrezap1;
    private javax.swing.JTextField txtrezap2;
    private javax.swing.JTextField txtrezl;
    private javax.swing.JTextField txtrezl1;
    private javax.swing.JTextField txtrezl2;
    private javax.swing.JTextField txttot;
    private javax.swing.JTextField txttot1;
    private javax.swing.JTextField txttot2;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotal1;
    private javax.swing.JTextField txttotal2;
    private javax.swing.JTextField txtvence;
    private javax.swing.JTextField txtvence1;
    private javax.swing.JTextField txtvence2;
    // End of variables declaration//GEN-END:variables
}
